version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart-pantry-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: smart_pantry
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
